### ISSUE TITLE
Extended ping function

### ISSUE THREAD

**Issue by lucky-lusa** [iris-connect/eps#11]
To give actuators an overview of the other clients available in the system and their connectivity status, we should extend the _ping function. 

The following requirements would be important

- _ping not only for individual clients, but for a permission group (e.g. app provider). The return value could then be an array of the respective stati
- record the eps version in the status
- in case of error not only a timeout or the hint that the request could not be delivered should be returned. it would be good if the error could be specified (no entry in sd, connection refused, timeout,...) to simplify debugging.

**Comment by adewes** [comment]
I have extended the ping function and improved the error messages generated by the message broker. Implementing a broadcast function seems quite complex and error-prone so I have opted to leave this to the client for now. I have implemented a `_directory` function instead that enables clients to e.g. retrieve all service directory entries for a given group, which should make it easy to subsequently generate `_ping` requests for all members of the group. Let me know if there's anything else that's missing.
