### ISSUE TITLE
Adapt log format to IRIS standard

### ISSUE THREAD

**Issue by lucky-lusa** [iris-connect/eps#12]
We have defined a standard for the IRIS log files in #202. It would be desirable if the EPS also logs in this format. Uniform log files make the accumulated log easier to read.

**Comment by adewes** [comment]
The log format can now be changed using the `--format`parameter (which is supported by all executables e.g. proxy, sd, eps). Currently it only support the value `iris`, i.e. `--format iris` will set the log format to the IRIS format, e.g.

```bash
eps --level debug --format iris server run
```
