### ISSUE TITLE
Request timeouts / rate limiting at IP/subnet level

### ISSUE THREAD

**Issue by lucky-lusa** [iris-connect/eps#14]
There is a requirement to implement request timeouts and rate limiting at ip level (iris-connect/backlog#187). Are there questions about the implementation? Or was everything already settled?

**Comment by hey-johnnypark** [comment]
Ideas:

- Limit on payload size
- Limit on transactions / s

**Comment by hey-johnnypark** [comment]
@adewes will come up with an initial suggestion based on experience in other projects.

**Comment by adewes** [comment]
This is implemented in version `0.1.55`.
